[package]
name = "vial-srv"
version = "0.3.0"
edition = "2024"
description = """
Framework-agnostic server logic for Vial
"""
readme = "README.md"
homepage = "https://github.com/TheRustyPickle/Vial"
repository = "https://github.com/TheRustyPickle/Vial"
license = "MIT"
keywords = ["cli", "e2ee", "secret", "secure", "vault"]
categories = ["command-line-utilities"]

[dependencies]
chrono.workspace = true
diesel = { version = "2.3.7", features = ["chrono"] }
diesel-async = { version = "0.8.0", features = [
  "bb8",
  "migrations",
  "postgres",
] }
diesel_migrations = "2.3.1"
futures-util = "0.3.32"
rustls = { version = "0.23.37", features = ["ring"] }
thiserror = "2.0.18"
tokio.workspace = true
tokio-postgres = "0.7.17"
tokio-postgres-rustls = "0.13.0"
ulid = "1.2.1"
vial-shared.workspace = true
