[package]
name = "vial-cli"
version = "0.1.0"
edition = "2024"
description = """
CLI for creating and retrieving end-to-end encrypted secrets
"""
readme = "../README.md"
homepage = "https://github.com/TheRustyPickle/Vial"
repository = "https://github.com/TheRustyPickle/Vial"
license = "MIT"
keywords = ["cli", "e2ee", "secret", "secure", "vault"]
categories = ["command-line-utilities"]

[[bin]]
name = "vial"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
base64 = "0.22.1"
chrono.workspace = true
clap = { version = "4.5.54", features = ["derive"] }
dirs = "6.0.0"
reqwest = { version = "0.13.1", features = ["blocking", "json"] }
rpassword = "7.4.0"
serde.workspace = true
serde_json.workspace = true
vial-core.workspace = true
vial-shared.workspace = true
