[package]
name = "vial-core"
version = "0.2.0"
edition = "2024"
description = """
Crypto primitives for encrypting / decrypting for Vial
"""
readme = "README.md"
homepage = "https://github.com/TheRustyPickle/Vial"
repository = "https://github.com/TheRustyPickle/Vial"
license = "MIT"
keywords = ["cli", "e2ee", "secret", "secure", "vault"]
categories = ["command-line-utilities"]

[dependencies]
aead = "0.6.1"
anyhow.workspace = true
argon2 = { version = "0.5.3", default-features = false, features = ["std"] }
base64.workspace = true
chacha20poly1305 = { version = "0.11.0", features = ["zeroize"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rand = "0.10.2"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.4.3", features = ["wasm_js"] }
getrandom02 = { package = "getrandom", version = "0.2", features = ["js"] }
rand = "0.10.2"
